name: docker/ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4  

      - name: Build Docker Image
        run: docker build -t app:1.0 .

      - name:
        run: docker run --rm app:1.0
